/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Filme;
import java.util.Date;

/**
 *
 * @author Luiz Eduardo
 */
public class CadastroFilmes extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFilmes
     */
    public CadastroFilmes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIddoFilme = new javax.swing.JLabel();
        lblTituloDoFilme = new javax.swing.JLabel();
        lblCadastroDeFilmes = new javax.swing.JLabel();
        lblDataDeEstreia = new javax.swing.JLabel();
        lblClassificacaoIndicativa = new javax.swing.JLabel();
        lblBilheteria = new javax.swing.JLabel();
        lblAvaliacaoDoPublico = new javax.swing.JLabel();
        txtTituloDoFilme = new javax.swing.JTextField();
        txtIdDoFilme = new javax.swing.JTextField();
        txtDataDeEstreia = new javax.swing.JTextField();
        txtClassificacaoIndicativa = new javax.swing.JTextField();
        txtBilheteria = new javax.swing.JTextField();
        txtAvaliacaoDoPublico = new javax.swing.JTextField();
        btnSalvarFilme = new javax.swing.JButton();
        btnCancelarFilme = new javax.swing.JButton();
        lblDiretor = new javax.swing.JLabel();
        txtDiretorFilme = new javax.swing.JTextField();
        lblSinopseFilme = new javax.swing.JLabel();
        paneTxtSinopse = new javax.swing.JScrollPane();
        txtSinopseFilme = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIddoFilme.setText("Id do Filme:");

        lblTituloDoFilme.setText("Título do Filme:");

        lblCadastroDeFilmes.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        lblCadastroDeFilmes.setText("Cadastro De Filmes");

        lblDataDeEstreia.setText("Data de Estreia:");

        lblClassificacaoIndicativa.setText("Classificação Indicativa:");

        lblBilheteria.setText("Bilheteria:");

        lblAvaliacaoDoPublico.setText("Avaliação do Público:");

        btnSalvarFilme.setText("Salvar");
        btnSalvarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarFilmeActionPerformed(evt);
            }
        });

        btnCancelarFilme.setText("Cancelar");
        btnCancelarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFilmeActionPerformed(evt);
            }
        });

        lblDiretor.setText("Diretor:");

        lblSinopseFilme.setText("Sinopse:");

        txtSinopseFilme.setColumns(20);
        txtSinopseFilme.setRows(5);
        paneTxtSinopse.setViewportView(txtSinopseFilme);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paneTxtSinopse)
                    .addComponent(txtBilheteria, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTituloDoFilme, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdDoFilme)
                    .addComponent(txtDataDeEstreia, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtClassificacaoIndicativa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAvaliacaoDoPublico, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 458, Short.MAX_VALUE)
                        .addComponent(btnCancelarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDiretorFilme, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCadastroDeFilmes)
                            .addComponent(lblBilheteria)
                            .addComponent(lblIddoFilme)
                            .addComponent(lblTituloDoFilme)
                            .addComponent(lblDataDeEstreia)
                            .addComponent(lblClassificacaoIndicativa)
                            .addComponent(lblAvaliacaoDoPublico)
                            .addComponent(lblDiretor)
                            .addComponent(lblSinopseFilme))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCadastroDeFilmes)
                .addGap(18, 18, 18)
                .addComponent(lblIddoFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdDoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloDoFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTituloDoFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDataDeEstreia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataDeEstreia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClassificacaoIndicativa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassificacaoIndicativa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBilheteria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBilheteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvaliacaoDoPublico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAvaliacaoDoPublico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiretor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiretorFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSinopseFilme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneTxtSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFilmeActionPerformed
        // TODO add your handling code here:
        txtBilheteria.setText("");
        txtAvaliacaoDoPublico.setText("");
        txtClassificacaoIndicativa.setText("");
        txtIdDoFilme.setText("");
        txtTituloDoFilme.setText("");
        txtDataDeEstreia.setText("");
    }//GEN-LAST:event_btnCancelarFilmeActionPerformed

    private void btnSalvarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarFilmeActionPerformed
        // TODO add your handling code here:
        Date data = new Date(txtDataDeEstreia.getText());
        Filme novoFilme;
        novoFilme = new Filme(Integer.parseInt(txtIdDoFilme.getText()), txtTituloDoFilme.getText(), 
                txtDiretorFilme.getText(), data, Integer.parseInt(txtClassificacaoIndicativa.getText()), 
                Long.parseLong(txtBilheteria.getText()), Float.parseFloat(txtAvaliacaoDoPublico.getText()),
                txtSinopseFilme.getText());
    }//GEN-LAST:event_btnSalvarFilmeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarFilme;
    private javax.swing.JButton btnSalvarFilme;
    private javax.swing.JLabel lblAvaliacaoDoPublico;
    private javax.swing.JLabel lblBilheteria;
    private javax.swing.JLabel lblCadastroDeFilmes;
    private javax.swing.JLabel lblClassificacaoIndicativa;
    private javax.swing.JLabel lblDataDeEstreia;
    private javax.swing.JLabel lblDiretor;
    private javax.swing.JLabel lblIddoFilme;
    private javax.swing.JLabel lblSinopseFilme;
    private javax.swing.JLabel lblTituloDoFilme;
    private javax.swing.JScrollPane paneTxtSinopse;
    private javax.swing.JTextField txtAvaliacaoDoPublico;
    private javax.swing.JTextField txtBilheteria;
    private javax.swing.JTextField txtClassificacaoIndicativa;
    private javax.swing.JTextField txtDataDeEstreia;
    private javax.swing.JTextField txtDiretorFilme;
    private javax.swing.JTextField txtIdDoFilme;
    private javax.swing.JTextArea txtSinopseFilme;
    private javax.swing.JTextField txtTituloDoFilme;
    // End of variables declaration//GEN-END:variables
}
