/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author maxwell
 */
public class ListagemFilmes extends javax.swing.JFrame {

    /**
     * Creates new form ListagemFilmes
     */
    public ListagemFilmes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelFilmes = new javax.swing.JPanel();
        panelFilmeA = new javax.swing.JPanel();
        labelImagemA = new javax.swing.JLabel();
        buttonSessoesA = new javax.swing.JButton();
        scrollPaneA = new javax.swing.JScrollPane();
        textAreaA = new javax.swing.JTextArea();
        labelTituloFilmeA = new javax.swing.JLabel();
        panelFilmeB = new javax.swing.JPanel();
        lableImagemB = new javax.swing.JLabel();
        buttonSessoesB = new javax.swing.JButton();
        scrollPaneB = new javax.swing.JScrollPane();
        tesxtAreaB = new javax.swing.JTextArea();
        labelTituloFilmeB = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Filmes em cartaz");

        labelImagemA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filme1.png"))); // NOI18N

        buttonSessoesA.setText("Visualizar sessoes");
        buttonSessoesA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSessoesAActionPerformed(evt);
            }
        });

        textAreaA.setEditable(false);
        textAreaA.setColumns(20);
        textAreaA.setLineWrap(true);
        textAreaA.setRows(5);
        textAreaA.setText("Sinopse: Em um futuro não muito distante, uma equipe de cientistas brilhantes e astronautas aventureiros embarca em uma missão espacial inovadora. O objetivo deles é alcançar uma galáxia distante e explorar um planeta que dizem conter a chave para a vida eterna. No entanto, enquanto atravessam as regiões desconhecidas do universo, eles encontram anomalias cósmicas e enfrentam desafios perigosos que testam seus limites físicos e mentais. Em meio à vasta extensão do espaço, eles devem contar com sua desenvoltura e trabalho em equipe para sobreviver e descobrir os segredos extraordinários que os aguardam.");
        scrollPaneA.setViewportView(textAreaA);

        labelTituloFilmeA.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        labelTituloFilmeA.setText("A expedição estrelada");

        javax.swing.GroupLayout panelFilmeALayout = new javax.swing.GroupLayout(panelFilmeA);
        panelFilmeA.setLayout(panelFilmeALayout);
        panelFilmeALayout.setHorizontalGroup(
            panelFilmeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilmeALayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelImagemA)
                .addGap(18, 18, 18)
                .addGroup(panelFilmeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSessoesA)
                    .addComponent(labelTituloFilmeA)
                    .addComponent(scrollPaneA, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelFilmeALayout.setVerticalGroup(
            panelFilmeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilmeALayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelFilmeALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFilmeALayout.createSequentialGroup()
                        .addComponent(labelTituloFilmeA)
                        .addGap(20, 20, 20)
                        .addComponent(scrollPaneA, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSessoesA))
                    .addComponent(labelImagemA))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        lableImagemB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filme2.png"))); // NOI18N

        buttonSessoesB.setText("Visualizar sessoes");
        buttonSessoesB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSessoesBActionPerformed(evt);
            }
        });

        tesxtAreaB.setEditable(false);
        tesxtAreaB.setColumns(20);
        tesxtAreaB.setLineWrap(true);
        tesxtAreaB.setRows(5);
        tesxtAreaB.setText("Sinopse: Situado no hipnotizante mundo de ilusões e magia, \"Midnight Mirage\" segue a jornada de um talentoso jovem mágico chamado Alex. Após uma série de eventos enigmáticos, Alex descobre um livro antigo que contém a chave para desbloquear poderes inimagináveis. À medida que ele se aprofunda nos segredos das artes místicas, ele atrai a atenção de um ilusionista nefasto que fará de tudo para possuir a magia do livro para si mesmo. Com seus amigos ao seu lado, Alex deve dominar suas novas habilidades e superar seu adversário em uma batalha de alto risco de ilusão e inteligência.");
        scrollPaneB.setViewportView(tesxtAreaB);

        labelTituloFilmeB.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        labelTituloFilmeB.setText("Miragem da meia noite");

        javax.swing.GroupLayout panelFilmeBLayout = new javax.swing.GroupLayout(panelFilmeB);
        panelFilmeB.setLayout(panelFilmeBLayout);
        panelFilmeBLayout.setHorizontalGroup(
            panelFilmeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFilmeBLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lableImagemB)
                .addGap(18, 18, 18)
                .addGroup(panelFilmeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloFilmeB)
                    .addComponent(scrollPaneB, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSessoesB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFilmeBLayout.setVerticalGroup(
            panelFilmeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFilmeBLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelFilmeBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelFilmeBLayout.createSequentialGroup()
                        .addComponent(labelTituloFilmeB)
                        .addGap(20, 20, 20)
                        .addComponent(scrollPaneB, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSessoesB))
                    .addComponent(lableImagemB))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFilmesLayout = new javax.swing.GroupLayout(panelFilmes);
        panelFilmes.setLayout(panelFilmesLayout);
        panelFilmesLayout.setHorizontalGroup(
            panelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFilmeA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFilmesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelFilmeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelFilmesLayout.setVerticalGroup(
            panelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFilmesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelFilmeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(615, 615, 615))
            .addGroup(panelFilmesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelFilmesLayout.createSequentialGroup()
                    .addGap(321, 321, 321)
                    .addComponent(panelFilmeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(322, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addGap(299, 299, 299))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSessoesBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSessoesBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSessoesBActionPerformed

    private void buttonSessoesAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSessoesAActionPerformed
        try {
            // TODO add your handling code here:

            new SelecaoDeSessao("Nome teste").setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(ListagemFilmes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_buttonSessoesAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSessoesA;
    private javax.swing.JButton buttonSessoesB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImagemA;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTituloFilmeA;
    private javax.swing.JLabel labelTituloFilmeB;
    private javax.swing.JLabel lableImagemB;
    private javax.swing.JPanel panelFilmeA;
    private javax.swing.JPanel panelFilmeB;
    private javax.swing.JPanel panelFilmes;
    private javax.swing.JScrollPane scrollPaneA;
    private javax.swing.JScrollPane scrollPaneB;
    private javax.swing.JTextArea tesxtAreaB;
    private javax.swing.JTextArea textAreaA;
    // End of variables declaration//GEN-END:variables
}
