/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author maxwell
 */
public class ListagemDeFilmesDinamica extends javax.swing.JFrame {

     private int filmeIndex;
    
    /**
     * Creates new form ListagemDeFilmesDinamica
     */
    public ListagemDeFilmesDinamica() {
        initComponents();
        this.filmeIndex = 0;
        this.changeMovie();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnFilmeAnterior = new javax.swing.JButton();
        btnProximoFilme = new javax.swing.JButton();
        tbbPainelDeFilmes = new javax.swing.JTabbedPane();
        tb1 = new javax.swing.JPanel();
        lblCartazFilme = new javax.swing.JLabel();
        lblTituloFilme = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSinopse = new javax.swing.JTextPane();
        btnSessaoQuatorzeHorasDub = new javax.swing.JButton();
        lblSessoesDub = new javax.swing.JLabel();
        btnSessaoQuinzeETrintaDub = new javax.swing.JButton();
        btnSessaoDezesseteHorasDub = new javax.swing.JButton();
        btnSessaoDezenoveETrintaDub = new javax.swing.JButton();
        btnSessaoVinteEUmaDub = new javax.swing.JButton();
        btnSessaoVinteEDuasETrintaDub = new javax.swing.JButton();
        btnSessaoQuatorzeHorasLeg = new javax.swing.JButton();
        lblSessoesLeg = new javax.swing.JLabel();
        btnSessaoQuinzeETrintaLeg = new javax.swing.JButton();
        btnSessaoDezesseteHorasLeg = new javax.swing.JButton();
        btnSessaoDezenoveETrintaLeg = new javax.swing.JButton();
        btnSessaoVinteEUmaLeg = new javax.swing.JButton();
        btnSessaoVinteEDuasETrintaLeg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        btnFilmeAnterior.setText("Filme Anterior");
        btnFilmeAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilmeAnteriorActionPerformed(evt);
            }
        });

        btnProximoFilme.setText("Próximo Filme");
        btnProximoFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoFilmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFilmeAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 527, Short.MAX_VALUE)
                .addComponent(btnProximoFilme)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFilmeAnterior)
                    .addComponent(btnProximoFilme))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 750, 90));

        lblCartazFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filme1.png"))); // NOI18N

        lblTituloFilme.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lblTituloFilme.setText("Uma Incrível Jornada Espacial");

        txtSinopse.setText("Synopsis: In a not-too-distant future, a team of brilliant scientists and adventurous astronauts embark on a groundbreaking space mission. Their objective is to reach a distant galaxy and explore a planet rumored to hold the key to eternal life. However, as they traverse the uncharted regions of the universe, they encounter cosmic anomalies and face perilous challenges that test their physical and mental limits. Amidst the vast expanse of space, they must rely on their resourcefulness and teamwork to survive and uncover the extraordinary secrets that await them.");
        jScrollPane1.setViewportView(txtSinopse);

        btnSessaoQuatorzeHorasDub.setText("14:00");

        lblSessoesDub.setText("Sessões dubladas disponíveis:");

        btnSessaoQuinzeETrintaDub.setText("15:30");

        btnSessaoDezesseteHorasDub.setText("17:00");

        btnSessaoDezenoveETrintaDub.setText("19:30");

        btnSessaoVinteEUmaDub.setText("21:00");

        btnSessaoVinteEDuasETrintaDub.setText("22:30");

        btnSessaoQuatorzeHorasLeg.setText("14:00");

        lblSessoesLeg.setText("Sessões legendadas disponíveis:");

        btnSessaoQuinzeETrintaLeg.setText("15:30");

        btnSessaoDezesseteHorasLeg.setText("17:00");

        btnSessaoDezenoveETrintaLeg.setText("19:30");

        btnSessaoVinteEUmaLeg.setText("21:00");

        btnSessaoVinteEDuasETrintaLeg.setText("22:30");

        javax.swing.GroupLayout tb1Layout = new javax.swing.GroupLayout(tb1);
        tb1.setLayout(tb1Layout);
        tb1Layout.setHorizontalGroup(
            tb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tb1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tb1Layout.createSequentialGroup()
                        .addComponent(lblCartazFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tb1Layout.createSequentialGroup()
                                .addComponent(lblTituloFilme)
                                .addGap(0, 79, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(tb1Layout.createSequentialGroup()
                        .addGroup(tb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSessoesLeg)
                            .addGroup(tb1Layout.createSequentialGroup()
                                .addComponent(btnSessaoQuatorzeHorasLeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSessaoQuinzeETrintaLeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSessaoDezesseteHorasLeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSessaoDezenoveETrintaLeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSessaoVinteEUmaLeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSessaoVinteEDuasETrintaLeg))
                            .addGroup(tb1Layout.createSequentialGroup()
                                .addGroup(tb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSessoesDub)
                                    .addGroup(tb1Layout.createSequentialGroup()
                                        .addComponent(btnSessaoQuatorzeHorasDub)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSessaoQuinzeETrintaDub)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSessaoDezesseteHorasDub)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSessaoDezenoveETrintaDub)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnSessaoVinteEUmaDub)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSessaoVinteEDuasETrintaDub)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tb1Layout.setVerticalGroup(
            tb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tb1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tb1Layout.createSequentialGroup()
                        .addComponent(lblTituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(lblCartazFilme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSessoesDub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSessaoQuatorzeHorasDub)
                    .addComponent(btnSessaoQuinzeETrintaDub)
                    .addComponent(btnSessaoDezesseteHorasDub)
                    .addComponent(btnSessaoDezenoveETrintaDub)
                    .addComponent(btnSessaoVinteEUmaDub)
                    .addComponent(btnSessaoVinteEDuasETrintaDub))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSessoesLeg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tb1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSessaoQuatorzeHorasLeg)
                    .addComponent(btnSessaoQuinzeETrintaLeg)
                    .addComponent(btnSessaoDezesseteHorasLeg)
                    .addComponent(btnSessaoDezenoveETrintaLeg)
                    .addComponent(btnSessaoVinteEUmaLeg)
                    .addComponent(btnSessaoVinteEDuasETrintaLeg))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        tbbPainelDeFilmes.addTab("tab1", tb1);

        jPanel2.add(tbbPainelDeFilmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(766, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFilmeAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilmeAnteriorActionPerformed
        // TODO add your handling code here:
        this.filmeIndex -= 1;
        this.changeMovie();
    }//GEN-LAST:event_btnFilmeAnteriorActionPerformed
    
    private void btnProximoFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoFilmeActionPerformed
        this.filmeIndex += 1;
        this.changeMovie();
    }//GEN-LAST:event_btnProximoFilmeActionPerformed

    private void changeMovie() {
        this.setFilme();
        
        if(filmeIndex >= Principal.filmes.size() - 1) {
            btnProximoFilme.setEnabled(false);
        } else {
            btnProximoFilme.setEnabled(true);
        }
        
        if(filmeIndex > 0) {
            btnFilmeAnterior.setEnabled(true);
        } else {
            btnFilmeAnterior.setEnabled(false);
        }
    }
    
    private void setFilme(){
        assert(filmeIndex >= 0);
        assert(filmeIndex < Principal.filmes.size());
        
        var filme = Principal.filmes.get(filmeIndex);
        
        lblTituloFilme.setText(filme.getTitulo());
        txtSinopse.setText(filme.getSinopse());
        
        URL url;
        BufferedImage image;
        
        try {
            url = new URL(filme.getImageUrl());
            image = ImageIO.read(url);     
            lblCartazFilme.setIcon(new ImageIcon(image));
        } catch (MalformedURLException e) {
            // erro 
            JOptionPane.showMessageDialog(null, 
                    "Não foi possivel carregar a imagem deste filme.");
        } catch (IOException ex) {
            //erro  
            JOptionPane.showMessageDialog(null, 
                    "Não foi possivel carregar a imagem deste filme.");
         }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListagemDeFilmesDinamica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListagemDeFilmesDinamica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListagemDeFilmesDinamica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListagemDeFilmesDinamica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListagemDeFilmesDinamica().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFilmeAnterior;
    private javax.swing.JButton btnProximoFilme;
    private javax.swing.JButton btnSessaoDezenoveETrintaDub;
    private javax.swing.JButton btnSessaoDezenoveETrintaLeg;
    private javax.swing.JButton btnSessaoDezesseteHorasDub;
    private javax.swing.JButton btnSessaoDezesseteHorasLeg;
    private javax.swing.JButton btnSessaoQuatorzeHorasDub;
    private javax.swing.JButton btnSessaoQuatorzeHorasLeg;
    private javax.swing.JButton btnSessaoQuinzeETrintaDub;
    private javax.swing.JButton btnSessaoQuinzeETrintaLeg;
    private javax.swing.JButton btnSessaoVinteEDuasETrintaDub;
    private javax.swing.JButton btnSessaoVinteEDuasETrintaLeg;
    private javax.swing.JButton btnSessaoVinteEUmaDub;
    private javax.swing.JButton btnSessaoVinteEUmaLeg;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCartazFilme;
    private javax.swing.JLabel lblSessoesDub;
    private javax.swing.JLabel lblSessoesLeg;
    private javax.swing.JLabel lblTituloFilme;
    private javax.swing.JPanel tb1;
    private javax.swing.JTabbedPane tbbPainelDeFilmes;
    private javax.swing.JTextPane txtSinopse;
    // End of variables declaration//GEN-END:variables
}
