/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

/**
 *
 * @author Luiz Eduardo
 */
public class SelecaoDeSessao extends javax.swing.JFrame {

    /**
     * Creates new form SelecaoDeSessao
     */
    public SelecaoDeSessao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCartazFilme = new javax.swing.JLabel();
        lblTituloDoFilme = new javax.swing.JLabel();
        btnQuatorzeHorasLegendado = new javax.swing.JButton();
        btnDezesseisHorasDublado = new javax.swing.JButton();
        scrSinopse = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        lblClassificacaoIndicativa = new javax.swing.JLabel();
        lblDublado = new javax.swing.JLabel();
        lblSalaUm = new javax.swing.JLabel();
        btnVinteHorasDublado = new javax.swing.JButton();
        btnDezoitoHorasDublado = new javax.swing.JButton();
        btnZeroHorasDublado = new javax.swing.JButton();
        btnVinteEDuasHorasDublado = new javax.swing.JButton();
        lblLegendado = new javax.swing.JLabel();
        lblSala2 = new javax.swing.JLabel();
        btnQuatorzeHorasDublado = new javax.swing.JButton();
        btnDezesseisHorasLegendado = new javax.swing.JButton();
        btnDezoitoHorasLegendado = new javax.swing.JButton();
        btnVinteHorasLegendado = new javax.swing.JButton();
        btnVinteEDuasHorasLegendado = new javax.swing.JButton();
        btnZeroHorasLegendado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCartazFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filme1.png"))); // NOI18N
        lblCartazFilme.setText("jLabel1");

        lblTituloDoFilme.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblTituloDoFilme.setText("A expedição estrelada");

        btnQuatorzeHorasLegendado.setText("14:00");
        btnQuatorzeHorasLegendado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuatorzeHorasLegendadoActionPerformed(evt);
            }
        });

        btnDezesseisHorasDublado.setText("16:00");
        btnDezesseisHorasDublado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDezesseisHorasDubladoActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setText("Sinopse: Em um futuro não muito distante, uma equipe de cientistas brilhantes e astronautas aventureiros embarca em uma missão espacial inovadora. O objetivo deles é alcançar uma galáxia distante e explorar um planeta que dizem conter a chave para a vida eterna. No entanto, enquanto atravessam as regiões desconhecidas do universo, eles encontram anomalias cósmicas e enfrentam desafios perigosos que testam seus limites físicos e mentais. Em meio à vasta extensão do espaço, eles devem contar com sua desenvoltura e trabalho em equipe para sobreviver e descobrir os segredos extraordinários que os aguardam.");
        scrSinopse.setViewportView(jTextArea2);

        lblClassificacaoIndicativa.setText("Classificação indicativa: 14 anos");

        lblDublado.setText("Dublado:");

        lblSalaUm.setText("Sala 1:");

        btnVinteHorasDublado.setText("20:00");

        btnDezoitoHorasDublado.setText("18:00");

        btnZeroHorasDublado.setText("00:00");

        btnVinteEDuasHorasDublado.setText("22:00");

        lblLegendado.setText("Legendado:");

        lblSala2.setText("Sala 2:");

        btnQuatorzeHorasDublado.setText("14:00");
        btnQuatorzeHorasDublado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuatorzeHorasDubladoActionPerformed(evt);
            }
        });

        btnDezesseisHorasLegendado.setText("16:00");
        btnDezesseisHorasLegendado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDezesseisHorasLegendadoActionPerformed(evt);
            }
        });

        btnDezoitoHorasLegendado.setText("18:00");

        btnVinteHorasLegendado.setText("20:00");

        btnVinteEDuasHorasLegendado.setText("22:00");

        btnZeroHorasLegendado.setText("00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCartazFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(scrSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClassificacaoIndicativa)
                                    .addComponent(lblTituloDoFilme))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDublado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnQuatorzeHorasDublado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDezesseisHorasDublado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDezoitoHorasDublado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVinteHorasDublado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVinteEDuasHorasDublado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZeroHorasDublado))
                            .addComponent(lblSalaUm)
                            .addComponent(lblLegendado)
                            .addComponent(lblSala2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnQuatorzeHorasLegendado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDezesseisHorasLegendado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDezoitoHorasLegendado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVinteHorasLegendado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVinteEDuasHorasLegendado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnZeroHorasLegendado)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloDoFilme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblClassificacaoIndicativa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrSinopse, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCartazFilme))
                .addGap(17, 17, 17)
                .addComponent(lblDublado, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSalaUm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDezesseisHorasDublado)
                    .addComponent(btnDezoitoHorasDublado)
                    .addComponent(btnVinteHorasDublado)
                    .addComponent(btnVinteEDuasHorasDublado)
                    .addComponent(btnZeroHorasDublado)
                    .addComponent(btnQuatorzeHorasDublado))
                .addGap(18, 18, 18)
                .addComponent(lblLegendado)
                .addGap(18, 18, 18)
                .addComponent(lblSala2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuatorzeHorasLegendado)
                    .addComponent(btnDezesseisHorasLegendado)
                    .addComponent(btnDezoitoHorasLegendado)
                    .addComponent(btnVinteHorasLegendado)
                    .addComponent(btnVinteEDuasHorasLegendado)
                    .addComponent(btnZeroHorasLegendado))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuatorzeHorasLegendadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuatorzeHorasLegendadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuatorzeHorasLegendadoActionPerformed

    private void btnDezesseisHorasDubladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDezesseisHorasDubladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDezesseisHorasDubladoActionPerformed

    private void btnQuatorzeHorasDubladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuatorzeHorasDubladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuatorzeHorasDubladoActionPerformed

    private void btnDezesseisHorasLegendadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDezesseisHorasLegendadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDezesseisHorasLegendadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecaoDeSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecaoDeSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecaoDeSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecaoDeSessao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecaoDeSessao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDezesseisHorasDublado;
    private javax.swing.JButton btnDezesseisHorasLegendado;
    private javax.swing.JButton btnDezoitoHorasDublado;
    private javax.swing.JButton btnDezoitoHorasLegendado;
    private javax.swing.JButton btnQuatorzeHorasDublado;
    private javax.swing.JButton btnQuatorzeHorasLegendado;
    private javax.swing.JButton btnVinteEDuasHorasDublado;
    private javax.swing.JButton btnVinteEDuasHorasLegendado;
    private javax.swing.JButton btnVinteHorasDublado;
    private javax.swing.JButton btnVinteHorasLegendado;
    private javax.swing.JButton btnZeroHorasDublado;
    private javax.swing.JButton btnZeroHorasLegendado;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblCartazFilme;
    private javax.swing.JLabel lblClassificacaoIndicativa;
    private javax.swing.JLabel lblDublado;
    private javax.swing.JLabel lblLegendado;
    private javax.swing.JLabel lblSala2;
    private javax.swing.JLabel lblSalaUm;
    private javax.swing.JLabel lblTituloDoFilme;
    private javax.swing.JScrollPane scrSinopse;
    // End of variables declaration//GEN-END:variables
}
